# Site
name: "ISMRM Iberian Chapter"
title: "ISMRM Iberian Chapter"
description: "Website for the ISMRM Iberian Chapter"
meta_description: "Website for the ISMRM Iberian Chapter."
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
paginate: 4
email: "iberianchapter@gmail.com"

# Authors
authors:
  diego:
    name: Diego
    display_name: Diego
    gravatar: 16309852?v=4
    # email: wowthemesnet@gmail.com
    web: https://twitter.com/dherarr
    # description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  ana:
    name: Ana
    display_name: Ana
    gravatar: 71497582?v=4
    #   email: wowthemesnet@gmail.com
    web: https://twitter.com/FoutoAna
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
  teresa:
    name: Teresa
    display_name: Teresa
    gravatar: 49432711?v=4
    web: https://twitter.com/TeresaM2Correia
  rita:
    name: Rita
    display_name: Rita
    gravatar: 36857476?v=4
    web: https://twitter.com/RitaGNunes

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Other
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
